Add option to define fulcio and rekor url (#20)
Now can set Fulcio and Rekor in the resource level

example
```
resource "cosign_sign" "foo" {
  image = blabla/xoxo@sha256:23432432

  fulcio_url = "https://my_custom_fulcio"
  rekor_url = "https://my_custom_rekor"
}
```


However running the tests and running `cosign` itself and point for
example to rekor/fulcio at staging env it return the error

```
Error: signing [ghcr.io/cpanato/testing-ci-providers:latest]: getting signer: getting key from Fulcio: verifying SCT: ctfe public key not found for payload. Check your TUF root (see cosign initialize) or set a custom key with env var SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
main.go:74: error during command execution: signing [ghcr.io/cpanato/testing-ci-providers:latest]: getting signer: getting key from Fulcio: verifying SCT: ctfe public key not found for payload. Check your TUF root (see cosign initialize) or set a custom key with env var SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
```

So looks like we need to run the cosign initialize first

Fixes: #8